#!/usr/bin/env bash

export EDITOR=nvim
export PATH=${HOME}/.local/bin:${PATH}
if [[ $(hostnamectl hostname) = "leviathan" ]]; then
    export PATH=${PATH}:/opt/afni:/opt/cuda
fi
export TF_CPP_MIN_LOG_LEVEL=3
export LD_LIBRARY_PATH=/opt/cuda/lib64
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
export DOTS=${HOME}/projects/dots
export HISTFILE=${HOME}/.bash_history

export HISTFILESIZE=
export HISTSIZE=
PROMPT_COMMAND='history -a; history -c; history -r'
# See [XDG Base Directory Specs](https://bit.ly/3zFJEV5).
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state
export XDG_CACHE_HOME=${HOME}/.cache
export R_LIBS="${HOME}/.local/lib/R"

# DATA
export PYTHONPATH=${XDG_DATA_HOME}/python
export MYSQL_HISTFILE=${XDG_DATA_HOME}/mysql_history
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history
export LESSHISTFILE=${XDG_DATA_HOME}/lesshist
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export TEXMFHOME=$XDG_DATA_HOME/texmf
# CACHE
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
# CONFIGS
export GOPATH=${XDG_CONFIG_HOME}/go
export JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME}/jupyter
export STARDICT_DATA_DIR=${XDG_CONFIG_HOME}
export XINITRC=${XDG_CONFIG_HOME}/X11/xinitrc
export INPUTRC=${XDG_CONFIG_HOME}/readline/inputrc
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export TASKDATA=${XDG_CONFIG_HOME}/task
# export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc

# Find and source configs.
source ${DOTS}/shell/bash_aliases
source ${DOTS}/shell/prompt_colors
source ${XDG_CONFIG_HOME}/lf/pretty_lf.sh
source ${XDG_CONFIG_HOME}/fzf/fzfrc

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash


# Shell options
shopt -s checkjobs
shopt -s histappend

if [[ `uname -n` = 'ideapad' ]]
then
    R='\[\e[0;90m\]'  # Dark Gray brackets
    G='\[\e[0;96m\]'  # Bright Cyan username
    B='\[\e[0;94m\]'  # Bright Blue '@'
    C='\[\e[0;95m\]'  # Bright Magenta hostname
    W='\[\e[0;97m\]'  # White ':'
    Y='\[\e[0;92m\]'  # Bright Green working directory
    P='\[\e[0;93m\]'  # Bright Yellow '$'
    F='\[\e[0m\]'     # Reset
fi

PS1="${R}[${G}\u${B}@${C}\h${W}: ${Y}\w${R}]${P}\$${F} "


export NODE_OPTIONS=--openssl-legacy-provider

[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh
