#!/bin/bash
#
# ░█▀▄░█▀█░█▀▀░█░█░░░█▀█░█░░░▀█▀░█▀█░█▀▀░█▀▀░█▀▀
# ░█▀▄░█▀█░▀▀█░█▀█░░░█▀█░█░░░░█░░█▀█░▀▀█░█▀▀░▀▀█
# ░▀▀░░▀░▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀


alias vi="/usr/bin/nvim"
alias dbworkbench="/usr/bin/nvim -c \"DBUI\""
alias ls="ls -v --color=auto --group-directories-first -1"
alias grep="grep --color=auto"
alias less="less --quit-if-one-screen -X --RAW-CONTROL-CHARS"
alias octave="octave --silent"
alias sudo="sudo "
alias pqiv="pqiv 2> /dev/null"
## Works with .pptx and .docx POST DEPRECATION
alias convert2pdf="soffice --headless --convert-to pdf"
alias py2nb="jupytext --to notebook"
alias figlet="figlet -f /home/nikin/projects/dots/local/share/figlet/pagga.tlf"


function hb() {
    # Handle block devices
    local mntpt selection
    mntpt="/run/media/$USER"

    selection="$(ls -1 --color=never $mntpt | fzf)" || return 1
    selection="${mntpt}/${selection}"

    if [ "$1" = "-u" ]; then
        local device
        device=$(findmnt -n -o SOURCE "$selection")
        udiskie-umount $device || return 1
        return 0
    fi

    if [ -d "$selection" ]; then
        cd "$selection"
    fi

    return 0
}


# Function Definitions
function weather() {
  curl wttr.in/${1}
}


function def() {
    sdcv -n --utf8-output --color "$@" 2>&1 | \
        fold --width=$(tput cols) | \
        less --quit-if-one-screen -RX
    }

function shutdown() {
    syncnotes
    /usr/bin/shutdown $1    
}
