-- Check https://www.overleaf.com/learn/latex/List_of_Greek_letters_and_math_symbols

return {
    -- Lowercase 
    parse({ trig = "alpha",      desc = "α (alpha) – angle, coefficient" }, "\\alpha"),
    parse({ trig = "beta",       desc = "β (beta) – coefficient, velocity ratio" }, "\\beta"),
    parse({ trig = "gamma",      desc = "γ (gamma) – Lorentz factor, Euler constant" }, "\\gamma"),
    parse({ trig = "delta",      desc = "δ (delta) – small change, Dirac delta" }, "\\delta"),
    parse({ trig = "epsilon",    desc = "ε (epsilon) – error, strain, permittivity" }, "\\epsilon"),
    parse({ trig = "zeta",       desc = "ζ (zeta) – damping ratio" }, "\\zeta"),
    parse({ trig = "eta",        desc = "η (eta) – efficiency, viscosity" }, "\\eta"),
    parse({ trig = "theta",      desc = "θ (theta) – angle, polar coordinate" }, "\\theta"),
    parse({ trig = "iota",       desc = "ι (iota) – inclusion map" }, "\\iota"),
    parse({ trig = "kappa",      desc = "κ (kappa) – curvature, thermal conductivity" }, "\\kappa"),
    parse({ trig = "lambda",     desc = "λ (lambda) – wavelength, eigenvalue" }, "\\lambda"),
    parse({ trig = "mu",         desc = "μ (mu) – micro prefix, coefficient of friction" }, "\\mu"),
    parse({ trig = "nu",         desc = "ν (nu) – frequency, kinematic viscosity" }, "\\nu"),
    parse({ trig = "xi",         desc = "ξ (xi) – random variable" }, "\\xi"),
    parse({ trig = "pi",         desc = "π (pi) – circle constant" }, "\\pi"),
    parse({ trig = "rho",        desc = "ρ (rho) – density, resistivity" }, "\\rho"),
    parse({ trig = "sigma",      desc = "σ (sigma) – standard deviation, stress" }, "\\sigma"),
    parse({ trig = "tau",        desc = "τ (tau) – time constant, torque" }, "\\tau"),
    parse({ trig = "upsilon",    desc = "υ (upsilon) – specific volume" }, "\\upsilon"),
    parse({ trig = "phi",        desc = "φ (phi) – golden ratio, potential" }, "\\phi"),
    parse({ trig = "chi",        desc = "χ (chi) – chi-square statistic" }, "\\chi"),
    parse({ trig = "psi",        desc = "ψ (psi) – wavefunction" }, "\\psi"),
    parse({ trig = "omega",      desc = "ω (omega) – angular frequency" }, "\\omega"),
    -- Variant lowercase
    parse({ trig = "varepsilon", desc = "ϵ (varepsilon) – small quantity" }, "\\varepsilon"),
    parse({ trig = "vartheta",   desc = "ϑ (vartheta) – alternate theta" }, "\\vartheta"),
    parse({ trig = "varpi",      desc = "ϖ (varpi) – variant pi" }, "\\varpi"),
    parse({ trig = "varrho",     desc = "ϱ (varrho) – variant rho" }, "\\varrho"),
    parse({ trig = "varsigma",   desc = "ς (varsigma) – word-final sigma" }, "\\varsigma"),
    parse({ trig = "varphi",     desc = "ϕ (varphi) – alternate phi" }, "\\varphi"),
    -- Uppercase Greek
    parse({ trig = "Gamma",      desc = "Γ (Gamma) – gamma function" }, "\\Gamma"),
    parse({ trig = "Delta",      desc = "Δ (Delta) – finite change" }, "\\Delta"),
    parse({ trig = "Epsilon",    desc = "Ε (Epsilon)" }, "\\Epsilon"),
    parse({ trig = "Theta",      desc = "Θ (Theta) – big-Theta complexity" }, "\\Theta"),
    parse({ trig = "Lambda",     desc = "Λ (Lambda)– eigenvalue operator" }, "\\Lambda"),
    parse({ trig = "Xi",         desc = "Ξ (Xi) – random variable" }, "\\Xi"),
    parse({ trig = "Pi",         desc = "Π (Pi) – product operator" }, "\\Pi"),
    parse({ trig = "Sigma",      desc = "Σ (Sigma) – summation operator" }, "\\Sigma"),
    parse({ trig = "Upsilon",    desc = "Υ (Upsilon)" }, "\\Upsilon"),
    parse({ trig = "Phi",        desc = "Φ (Phi) – magnetic flux" }, "\\Phi"),
    parse({ trig = "Psi",        desc = "Ψ (Psi) – quantum state" }, "\\Psi"),
    parse({ trig = "Omega",      desc = "Ω (Omega) – electrical resistance" }, "\\Omega"),
}
