#!/bin/bash

# ░█▀▄░█▀█░█▀▀░█░█░█▀▄░█▀▀
# ░█▀▄░█▀█░▀▀█░█▀█░█▀▄░█░░
# ░▀▀░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀

# Environment Variables
export EDITOR=nvim
export TERM=st-256color
export PATH=${PATH}:${HOME}/.local/bin
#
# XDG Base Directory Specs. See: (https://bit.ly/3zFJEV5).
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state
export XDG_CACHE_HOME=${HOME}/.cache
# State
export HISTFILE="${XDG_STATE_HOME}"/bash/history
# Data
export MYSQL_HISTFILE="${XDG_DATA_HOME}"/mysql_history
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export LESSHISTFILE=${XDG_DATA_HOME}/lesshist
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export TEXMFHOME=$XDG_DATA_HOME/texmf
# Paths again
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
# Cache
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
# Configs
export GOPATH=${XDG_CONFIG_HOME}/go
export JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME}/jupyter
export STARDICT_DATA_DIR=${XDG_CONFIG_HOME}
export PYTHONPATH=${XDG_DATA_HOME}/python
export XINITRC=${XDG_CONFIG_HOME}/X11/xinitrc
export INPUTRC=${XDG_CONFIG_HOME}/readline/inputrc
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

export TF_CPP_MIN_LOG_LEVEL=1
export DOTS=${HOME}/repos/dots

# Find and source configs.
source ${DOTS}/config/bash/bash_aliases
source ${DOTS}/config/bash/prompt_colors
source ${XDG_CONFIG_HOME}/fzf/fzfrc
source ${XDG_CONFIG_HOME}/lf/pretty_lf.sh

# Shell options
shopt -s checkjobs

PS1="${R}[${G}\u${P}@${B}\h${W}: ${Y}\W${R}]${C}\$${F} "
