Section "InputClass"
    Identifier "TrackPoint tuning"
    MatchProduct "TPPS/2 IBM TrackPoint"
    MatchIsPointer "on"
    Driver "libinput"
    Option "libinput Accel Speed" "-1"
    Option "libinput Accel Profile Enabled" "0, 1, 0"
EndSection
