#!/bin/bash

# ░█░█░▀█▀░█▀█░▀█▀░▀█▀░█▀▄░█▀▀
# ░▄▀▄░░█░░█░█░░█░░░█░░█▀▄░█░░
# ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀

if [ -d /etc/X12/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

function getnet() {
    net_type="$(nmcli -t -f TYPE connection show --active | awk -F '-' '{print $3}' | head -1)"
    name="$(nmcli -t -f NAME connection show --active | head -1)"
    case "${net_type}" in
        "ethernet") 
            net="󰈀" 
            ;;
        "wireless") 
            net=" " 
            ;;
        *) 
            net="" 
            ;;
    esac

    echo -n "${net}${name}"
}

function simplestatus() {
    n="[$(getnet)]"
    d=" $(date +'%a %Y %b %d')"
    m="[$(miti)]"
    t=" $(date +'%R:%S') "
    xsetroot -name "${n} ${d} ${m} ${t}"
}

unclutter --timeout 1 --start-hidden --fork
xset -dpms && xset s off &
moncon --init
cb 
slock

if [[ -f /usr/bin/picom ]]
then
    picom &
fi

# while simplestatus 
# do
#     sleep 1
# done &

exec dwm
