# ░█░█░▀█▀░█▀█░▀█▀░▀█▀░█▀▄░█▀▀
# ░▄▀▄░░█░░█░█░░█░░░█░░█▀▄░█░░
# ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀

unclutter --timeout 1 --start-hidden --fork
xset -dpms && xset s off &
externalmonitor

cb ${HOME}/pics/wallpapers/black-pixelated.jpg

slock

while xsetroot -name "[$(hostname -i)] [$(miti)] [$(date +'%Y %b %d %a')] [$(date +'%R')]" 
do
    sleep 59
done&

exec dwm
