# ░█░█░▀█▀░█▀█░▀█▀░▀█▀░█▀▄░█▀▀
# ░▄▀▄░░█░░█░█░░█░░░█░░█▀▄░█░░
# ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀

unclutter --timeout 1 --start-hidden --fork
xset -dpms && xset s off &
dualmonitor

cb ${HOME}/pics/wallpapers/arch_ascii_art.png

slock

while xsetroot -name "[$(miti)] [$(date +'%Y %b %d %a')] [$(date +'%R')]" 
do
    sleep 59
done&

exec dwm

